# -*- coding: utf-8 -*-
"""git-mod hw1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eAZVW6n86l-ir3dDvgrmwXZE9vU3UjfD

Reading the data from a csv file and performing hypothesis testing - whether or not to reject null hypothesis
"""

import numpy as np
import pandas as pd
from scipy import stats
ercot = pd.read_csv('20190101-20191231 ERCOT Real-time Price.csv')
ercot['Date'] = pd.to_datetime(ercot['Date'])
ercot

"""
Now, test the hypothesis that the mean of `Price` for zone `LZ_HOUSTON` is $30$ at the significance level $5\%$."""

#avg=ercot[ercot['Zone'] == 'LZ_HOUSTON']['Price'].mean()
houstonVal = ercot[ercot['Zone'] == 'LZ_HOUSTON']['Price']
houstonVal
out=stats.ttest_1samp(houstonVal,30)
out
# when testing data from standard normal distribution, where mean=0; null hypothesis is expected to be rejected

if out.pvalue>=0.05:
  print('Do not reject H0')
else:
  print('Reject H0')

"""We have obtained the $t$-statistic value as can be seen above. Then, we can also compute the degrees of freedom using `stats.t.cdf` to verify the $p$-value obtained above."""

print(stats.t.sf(abs(out.statistic), df=houstonCount)*2)

